---
- name: Setup for nfs server
  hosts: localhost
  gather_facts: no

  tasks:
    - name: make nfs_shared directory
      file:
        path: /home/vagrant/nfs_shared
        state: directory
        mode: 0777

    - name: configure /etc/exports
      become: yes
      lineinfile:
        path: /etc/exports
        line: /home/vagrant/nfs_shared 192.168.1.0/24(rw,sync)

    - name : nfs service restart
      become: yes
      service :
        name : nfs
        state : restarted

- name: Setup for nfs clients
  hosts: CentOS:Ubuntu
  gather_facts: no

  tasks:
    - name: make nfs_client directory
      file:
        path: /home/vagrant/nfs
        state: directory

    - name: mount point direcotry as client
      become: yes
      mount:
        name: /home/vagrant/nfs
        src: 192.168.1.10:/home/vagrant/nfs_shared
        fstype: nfs
        opts: nfsvers=3
        state: mounted

- name: Setup for nfs windows clients
  hosts: Win
  gather_facts: no

  tasks:
    - name: mount feature on
      win_feature:
        name: NFS-Client
        state: present

    - name: mount nfs_shared
      win_command: net use "z:" "\\192.168.1.10/home/vagrant/nfs_shared"

    - name: windows reboot
      win_reboot:
      
- name: Check mounting status for linux
  hosts: CentOS:Ubuntu
  gather_facts: no

  tasks:
    - name: linux NFS clients
      shell: mount | grep nfs_shared
      register: output
    - debug: var=output.stdout_lines

- name: Check mounting status for windows
  hosts: Win
  strategy: debug
  gather_facts: no

  tasks:
    - name: Windows NFS clients
      win_command: mount
      register: output
    - debug: var=output.stdout_lines